pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -conflict
      - check-success=test
      - title~=^Bump [^\s]+ from ([\d]+)\.([\d]+)\..+ to \1\.\2\..
    actions:
      merge:
        method: merge
